spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unihub
    username: postgres
    password: 7212Hey)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumer_group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  docker:
    compose:
      enabled: false
      file: src/main/docker/docker-compose.yaml
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    user: postgres
#    password: 7212Hey)
#    baseline-description: "init"
#    baseline-version: 0

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method

#server:
#  port: 8090