version: '3'

services:
  app:
    image: 'final:latest'
    build:
      context: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jwt_security
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=7212Hey)
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7212Hey)
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d